### ISSUE TITLE
能否上传下page/index.html的vue源码

### ISSUE THREAD

**Issue by kuizuo** [g0ngjie/ajax-proxy#2]
能否上传下page/index.html的vue源码,想借鉴下学习消息通信

**Comment by Nyakooo** [comment]
[ajax-intercepter-views](https://github.com/g0ngjie/ajax-intercepter-views)

**Comment by kytrun** [comment]
目前分仓库这种可能不便查看，开发者可以考虑把源码和构建产物整合一下吗，感谢开源。

**Comment by Nyakooo** [comment]
2月份找个时间会整合一下

**Comment by kytrun** [comment]
还有反馈一点bug：
1. 备份功能无效
2. 重定向的添加 header 功能疑似无效，白名单功能概念模糊，是填写具体的 url 用以排除？所以应该是黑名单？

谢谢！

**Comment by Nyakooo** [comment]
1. 备份功能会通过浏览器，下载一份默认名为backup的json文件。如果是windows系统的话，默认会在Downloads文件夹种。不过如果数据量过大会出现数据被截断的异常情况存在(例如响应数据500Kb左右)
2. “header”实际和“白名单”问题一样，存在一定的歧义。目前只支持修改现有的数据，还没有支持增加。

谢谢反馈~

**Comment by kytrun** [comment]
“备份功能无效”指的是下载文件出错，console 如图，Edge 浏览器 97.0.1072.62
![image](https://user-images.githubusercontent.com/32519285/150487084-8b55a527-f616-4112-b753-dffd442fdbb8.png)

**Comment by Nyakooo** [comment]
整合项目的时候排查这个问题

**Comment by Nyakooo** [comment]
1. 目前两个仓库已合并到主分支
2. 优化了一些存在异议的文案
3. 优化备份时可能存在异常情况的Code

重定向header疑似只能修改
我查阅了一些文档和源码，好像在Ajax出发send的时候，无法新增header。
```javascript
// lib.dom.d.ts => setRequestHeader
/**
 * Combines a header in author request headers.
 *
 * Throws an "InvalidStateError" DOMException if either state is not opened or the send() flag is set.
 *
 * Throws a "SyntaxError" DOMException if name is not a header name or if value is not a header value.
 */
setRequestHeader(name: string, value: string): void;
```
目前我在增加header的情况下还没有很好的解决办法。

备份功能目前只做了疑似会出现异常情况的修正，平时工作的时候也会经常使用，如有类似情况，会持续优化。

**Comment by kytrun** [comment]
开发调试很好用，谢谢！
另外发现一个类似的
https://chrome.google.com/webstore/detail/request-interceptor/bfgblailifedppfilabonohepkofbkpm
测试这个是可以添加删除 header 的，其中部分功能也蛮强大的，大佬有兴趣可以参考参考。
