### ISSUE TITLE
重定向功能自动去除自定义请求头问题

### ISSUE THREAD

**Issue by intfoo** [g0ngjie/ajax-proxy#22]
使用重定向功能，在转发后的请求中会去除自定义的请求头，目前测试2.1.0和2.1.4会有这个问题，使用1.9.8正常。
浏览器版本：Microsoft Edge
版本 106.0.1370.30 (正式版本) beta (64 位)

**Comment by Nyakooo** [comment]
版本 2.1.5 修复自定义请求头丢失问题

**Comment by intfoo** [comment]
> 

好的，感谢，但是edge商店里面还是2.1.3。另外release版本是否更新发布的太频繁了，稳定性会有所下降

**Comment by intfoo** [comment]
> 版本 2.1.5 修复自定义请求头丢失问题


好的，感谢，但是edge商店里面还是2.1.3。另外release版本是否更新发布的太频繁了，稳定性会有所下降

**Comment by Nyakooo** [comment]
由于项目早期设计存在缺陷，会有未发现的隐患。近期在重构项目，所以改动比较频繁。[v2.2.0](https://github.com/g0ngjie/ajax-proxy/releases/tag/v2.2.0) 版本之后会趋于稳定，不会再有太大的改动了。
之后如果有bug，就会以小版本迭代更新。

Edge商店审核没有Chrome那么快，估计要等一天才会看到最新版本
