### ISSUE TITLE
JSON编辑中，输入汉字时有问题

### ISSUE THREAD

**Issue by zangguojun** [g0ngjie/ajax-proxy#25]
<img width="117" alt="image" src="https://user-images.githubusercontent.com/49148972/197478458-ad0b8fe2-0298-41c5-a519-56df703b1b73.png">

**Comment by Nyakooo** [comment]
晚上会看下这个问题

**Comment by Nyakooo** [comment]
👉 (v2.2.1) 这个版本修复

**Comment by zangguojun** [comment]
OK  感谢
