### ISSUE TITLE
希望添加个可以自动添加规则的功能

### ISSUE THREAD

**Issue by Will-Leonardo** [g0ngjie/ajax-proxy#27]
自动添加当前页面 中某一类的请求例如 /api/xxxxx ，默认响应数据为真实请求的返回结果； （作者是否考虑添加这么一个功能？）

**Comment by Nyakooo** [comment]
这个功能有考虑过，但通过固定规则或者无规则全量收集会有以下问题：
1. 路径匹配方式：因为无法预知使用者具体收集的目标，在类似 **//foo.com/api/xxx** 中如果存在多次匹配，或一次批量请求中如果有多次命中，数据无法准确收集
2. 批量检测方式：因为数据都是做持久化存储，在不关闭的情况下（忘记关闭），容量很容易会达到上限，导致 *QUOTA_BYTES_PER_ITEM quota exceeded*

交互上目前也没有想好该如何做，近期内不会加入这个功能
