### ISSUE TITLE
安装后，拦截不好使

### ISSUE THREAD

**Issue by xiaolannuoyi** [g0ngjie/ajax-proxy#3]
今天重新安装又试了下 一开始安装并使用是不好使的 
只有切换 到重定向 在切换回拦截器 ，拦截才起效果。 感觉这应该是一个bug
作者有时间的话，可以看一下
![image](https://user-images.githubusercontent.com/21079721/155447867-9177fc56-dcf2-4dd2-a5a8-c06611e7b04d.png)

**Comment by xiaolannuoyi** [comment]
换了台电脑，就怎么都不好使了，怎么试都拦截不到，求作者看下，给个解决方法呗。 @g0ngjie

**Comment by Nyakooo** [comment]
这个原因主要是浏览器缓存导致的。在设置好拦截对象时，需要用户主动刷新一下才会生效。

**Comment by nianyi778** [comment]
> 这个原因主要是浏览器缓存导致的。在设置好拦截对象时，需要用户主动刷新一下才会生效。

已经刷新了很多次依然无效，有点崩溃

**Comment by xiaolannuoyi** [comment]
@lidakai  你切换试了么。我是切换后就好使了。切换 到重定向 在切换回拦截器 。

**Comment by Nyakooo** [comment]
https://github.com/g0ngjie/ajax-proxy/blob/main/Interceptor.test.json
可以试一下提供的测试用例，分别使用在 [掘金](https://juejin.cn/) 和 [百度翻译](https://fanyi.baidu.com/)
1. 掘金：直接在首页查看效果；
2. 百度翻译：随便翻译点内容即可；
