### ISSUE TITLE
修改响应体能否支持函数

### ISSUE THREAD

**Issue by pansong291** [g0ngjie/ajax-proxy#30]
同过函数修改响应体，比如返回的响应体是 JSON，但是并不想全部重写整个内容，只修改其中某个字段的值，其他字段仍按原来的

**Comment by Nyakooo** [comment]
增加函数式编程，关注 [v2.2.2](https://github.com/g0ngjie/ajax-proxy/releases/tag/v2.2.2) 版本

**Comment by Nyakooo** [comment]
商店已经发布，更新 v2.2.2 版本以上即可

**Comment by furylee** [comment]
> 

函数的使用方式能出个教程吗?目前我修改的都未生效

**Comment by Nyakooo** [comment]
> > 
> 
> 函数的使用方式能出个教程吗?目前我修改的都未生效

已补充: [README.func.md](https://github.com/g0ngjie/ajax-proxy/blob/master/README.func.md)
