### ISSUE TITLE
请求不能拦截

### ISSUE THREAD

**Issue by AaronChengHao** [g0ngjie/ajax-proxy#32]
有些url可以拦截，有些不能拦截，不知道是什么原因造成的。
![image](https://user-images.githubusercontent.com/20119217/216540545-98cc7f9b-63b2-44b9-a782-cf6767c23542.png)

**Comment by Nyakooo** [comment]
需要检查一下url是否存在动态参数，或看一下是否存在"空输入"(空格)等类似隐晦的问题
也可以参考一下 #28 #5，看是否存在相同问题
