### ISSUE TITLE
网站首页的地址要怎么配置拦截？

### ISSUE THREAD

**Issue by smanx** [g0ngjie/ajax-proxy#33]
网站里面的请求可以拦截，网站链接本身好像没法拦截到
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/20833594/224200342-9edce2c5-b768-42d0-b700-504c84b3a7e7.png">

**Comment by smanx** [comment]
这个是配置
<img width="900" alt="image" src="https://user-images.githubusercontent.com/20833594/224200772-7a4b483e-4c18-4b76-9628-62afbc9e9b33.png">

**Comment by Nyakooo** [comment]
content-type: text/html 格式返回的是HTML，【#29】这种是无法处理的。
开发者工具面板上 过滤器有 ”Fetch/XHR“，只能处理这里面的数据。
