### ISSUE TITLE
Hope to add some url matching rules.

### ISSUE THREAD

**Issue by zangguojun** [g0ngjie/ajax-proxy#34]
Now
<img width="182" alt="image" src="https://user-images.githubusercontent.com/49148972/224465890-5e212713-8ecd-47fa-807d-38d21a9ce2df.png">

Hope
Add StartWith, EndWith etc.
Even if they can use RE to achieve

**Comment by Nyakooo** [comment]
The "Normal" pattern is actually matched by "includes", so if you want to take "StartWith" or "EndWith" as the condition, it should meet the requirements
```js
switch (type) {
    case "normal":
        matched = url.includes(match);
        break;
    // ...
}
```

**Comment by zangguojun** [comment]
Thanks!
