### ISSUE TITLE
F12中数据没变化

### ISSUE THREAD

**Issue by ifreeWorld** [g0ngjie/ajax-proxy#35]
F12中数据没变化，但是js代码中接收到的数据变化了，是否是因为只是做了 JS 层的数据转换，并非是网络层的拦截，所有F12 抓包的数据还是之前的返回，期待作者回复

**Comment by Nyakooo** [comment]
因为 **XMLHttpRequest** 它的 **responseText** 包括其他被修改的属性，对应原生并不是 **writeable** 的。内部通过生成代理属性的方式而并非直接修改原生属性值，所以我们是无法在开发者面板上看到修改数据的
