### ISSUE TITLE
是否可以提供正则的例子。

### ISSUE THREAD

**Issue by Sir0xb** [g0ngjie/ajax-proxy#38]
想用正则匹配不同环境。试着使用：
*://xxx.com/*abc?* 这种。结果是不work的。

**Comment by Nyakooo** [comment]
把前面的*去掉应该就可以了
**://xxx.com/abc?** 这样试试
或者 **(http|https)://xxx.com/abc?**

**Comment by pansong291** [comment]
`.+:\/\/xxx\.com\/abc`
