### ISSUE TITLE
谷歌版本116.0.5845.96，使用拦截器会疯狂发送请求

### ISSUE THREAD

**Issue by ITYHG** [g0ngjie/ajax-proxy#42]
目前我的谷歌版本是116.0.5845.96，使用当前插件的拦截器拦截请求后，网络会疯狂的发送请求，且拦截不生效，mock数据不生效。

My current version of Google is 116.0.5845.96, after intercepting a request with the current plugin's blocker, the network will send requests like crazy, and the intercept does not work, mock data does not work.

**Comment by Nyakooo** [comment]
有没有尝试过其他接口拦截，或者强刷一下试试。

**Comment by Nyakooo** [comment]
![image](https://github.com/g0ngjie/ajax-proxy/assets/35398659/8d430dc6-dd5e-490b-a973-77104b04a556)
目前我使用的和你是同一个版本，测试下来没发现你说的这种现象。插件本身并没有轮询发送的逻辑，是否是当前业务请求存在这类问题导致的
