### ISSUE TITLE
登录宝塔官网会报错，导致无法登录

### ISSUE THREAD

**Issue by Antecer** [g0ngjie/ajax-proxy#43]
问题出现的网址(输入账户密码后点击登录就出错)：
https://www.bt.cn/bbs/member.php?mod=logging&action=login

问题截图：
![image](https://github.com/g0ngjie/ajax-proxy/assets/8684916/329ffb70-4480-4c00-935f-1224d43b5634)

实测，关闭全局拦截(或没有开启任何拦截规则) 均会报错。
只有禁止插件运行，才能正常登录。

**Comment by Nyakooo** [comment]
实测下来发现，宝塔官方会在页面第一个<script />标签之前插入自己的<script />。也就是导致登录时的 "**s**"变量出现 undefined。

因为托管时机是在”document_start“，需要页面加载时对其进行代理。所以针对这个问题，目前还没有较为友好的方式修复。

同样类似通过脚本注入方式的插件也会出现相同的问题。

![image](https://github.com/g0ngjie/ajax-proxy/assets/35398659/ac55752c-917c-45c7-9f90-adc6a911d7ec)

![20230818133945_rec_](https://github.com/g0ngjie/ajax-proxy/assets/35398659/f41606c9-05ca-4e3f-81ff-90514a29d311)

**Comment by Antecer** [comment]
我以为这种插件是通过chromeAPI对请求进行拦截的，没想到竟然也是通过html页面识别进行的处理。
试一试，把插件的js通过eval的方式直接注入到页面js环境，这样就不会留下一个script标签了。

**Comment by Nyakooo** [comment]
可以提个PR看下
