### ISSUE TITLE
是否考虑支持请求体修改

### ISSUE THREAD

**Issue by DomKing** [g0ngjie/ajax-proxy#44]
现在的代理，实际上只有对响应体的修改。
一些情况下，是需要对请求体做一定修改的，是否考虑支持？目前好像 setup 有三个参数，第一个就是 req，但是实际上并未用到。

**Comment by Nyakooo** [comment]
请求体修改相对复杂，例如大尺寸报文、流文件等，这些条件都需要考虑在内，不然就相当于一个半成品。
比如用户上传一个500M的PDF，需要做其他附件的平替操作。那预上传的文件存储就是一个问题。

req包含了请求地址、方法和请求体，实际上是为了做判断使用的

**Comment by DomKing** [comment]
> 请求体修改相对复杂，例如大尺寸报文、流文件等，这些条件都需要考虑在内，不然就相当于一个半成品。 比如用户上传一个500M的PDF，需要做其他附件的平替操作。那预上传的文件存储就是一个问题。
> 
> req包含了请求地址、方法和请求体，实际上是为了做判断使用的

可以分步支持，比如先支持 application/json 的body修改，再支持 formData 修改，接着支持其他的。请求前后都可以修改就比较完善了。

**Comment by Nyakooo** [comment]
我记得原型链上好像是无法直接支持修改报文的。如果说错请见谅~
一般来说这个需求可以通过三方服务方式实现。不过你希望数据是本地安全还是云端帮你保存安全。很多企业内网环境，这样的就相当于使用不了了。

**Comment by Nyakooo** [comment]
不过你可以fork此项目，加一些自己的东西在里面。
