### ISSUE TITLE
使用函数返回请求结果时应该写，麻烦给个示例

### ISSUE THREAD

**Issue by KilianShen** [g0ngjie/ajax-proxy#45]
![image](https://github.com/g0ngjie/ajax-proxy/assets/86402559/1e6f3c05-fc2b-40b8-9351-7ea8a48b8753)
尝试了很多写法都不行

**Comment by Nyakooo** [comment]
```ts
async function setup(req, res, next) {
  let override;
  if (res.status !== 200) {
    // 独立接口请求
    const res = await fetch("https://v1.hitokoto.cn/");
    const json = await res.json();
    override = {
      code: "000000",
      data: json,
    };
    // 日志输出
    console.log("override:", override);
  } else override = res.response;

  next({
    // 如果不传override，则返回""
    override,
    // 如果不传status，则返回customStatus
    status: 200,
  });
}
```

**Comment by Nyakooo** [comment]
> ![image](https://user-images.githubusercontent.com/86402559/269515063-1e6f3c05-fc2b-40b8-9351-7ea8a48b8753.png) 尝试了很多写法都不行

可以尝试使用简单的代码，或者打console.log方式看下是否有日志输出

**Comment by KilianShen** [comment]
已解决，多谢
async function setup(req, res, next) {
  let override;
  if (res.status !== 200) {
    // 独立接口请求
    const res = await fetch("https://v1.hitokoto.cn/");
    const json = await res.json();
       const result = Array.from({length:10},(x,i)=>{
        return { "title": `${i}每周四超级定投日--点石成金`,
          "activeTime": "20230921",
          "infoClass": "基金定投策略",
          "imgUrl": "https://ayfileres.yjbtest.com/attachment/public/ims-business-chance/760066257587270508"}
      });
    override = {
      code: 100,
      note:"成功",
      result,
    };
    // 日志输出
    console.log("override:", override);
  } else override = res.response;

  next({
    // 如果不传override，则返回""
    override,
    // 如果不传status，则返回customStatus
    status: 200,
  });
}

**Comment by KilianShen** [comment]
已解决，多谢
```js

async function setup(req, res, next) {
  let override;
  if (res.status !== 200) {
    // 独立接口请求
    const res = await fetch("https://v1.hitokoto.cn/");
    const json = await res.json();
       const result = Array.from({length:10},(x,i)=>{
        return { "title": `${i}每周四超级定投日--点石成金`,
          "activeTime": "20230921",
          "infoClass": "基金定投策略",
          "imgUrl": "https://ayfileres.yjbtest.com/attachment/public/ims-business-chance/760066257587270508"}
      });
    override = {
      code: 100,
      note:"成功",
      result,
    };
    // 日志输出
    console.log("override:", override);
  } else override = res.response;

  next({
    // 如果不传override，则返回""
    override,
    // 如果不传status，则返回customStatus
    status: 200,
  });
}

````
