### ISSUE TITLE
安装有其它同类型扩展时 Not Working

### ISSUE THREAD

**Issue by xianghongai** [g0ngjie/ajax-proxy#46]
- Chrome: Version 117.0.5938.149 (Official Build) (64-bit)
- OS: 22.04.1-Ubuntu

安装了 [ajax-interceptor-tools](https://chromewebstore.google.com/detail/kphegobalneikdjnboeiheiklpbbhncm)、[Mock:Intercept and directly return data](https://chrome.google.com/webstore/detail/kmphamhphplpcjcabjdjjklfjmgkmpba) 这类扩展时，本扩展不生效。

**Comment by Nyakooo** [comment]
同类功能扩展会冲突，不能同时安装使用
