### ISSUE TITLE
重定向和拦截器为什么不能一起用，唯神魔

### ISSUE THREAD

**Issue by HaoRangQi** [g0ngjie/ajax-proxy#49]
![PixPin_2024-01-02_16-47-28](https://github.com/g0ngjie/ajax-proxy/assets/37143191/5ed9d20f-6d90-4e27-8ba1-d2eab180ef46)

**Comment by Nyakooo** [comment]
拦截和重定向从实现方式上，分别在发起请求的前后，功能如果合并处理的话会加入大量的中间环节处理和暂存瞬时的请求状态。体积上和使用效率会受到很大影响。
