### ISSUE TITLE
确实存在问题，无法拦截

### ISSUE THREAD

**Issue by PPPPPPan** [g0ngjie/ajax-proxy#5]
确实存在问题，无法拦截，尝试切换以及刷新均不生效

**Comment by PPPPPPan** [comment]
找到原因了，chrome浏览器装有另一个类似的插件Ajax Interceptor，将其停用便解决问题了

**Comment by Nyakooo** [comment]
同类功能的插件一起使用，确实会存在冲突的问题。使用其中一种时，可以暂时将其它的插件关闭掉
