### ISSUE TITLE
命中拦截规则，但是然后的数据未生效

### ISSUE THREAD

**Issue by yangfeng20** [g0ngjie/ajax-proxy#51]
首先命中了规则：
![image](https://github.com/g0ngjie/ajax-proxy/assets/83114564/53e2b7ba-4dfe-4863-83a6-7013e3c06a37)

我设置的响应数据为：
![image](https://github.com/g0ngjie/ajax-proxy/assets/83114564/dcafd91b-cb5c-49a2-b094-4fe93cb0f88b)

浏览者开发者工具中查看数据未修改：
![image](https://github.com/g0ngjie/ajax-proxy/assets/83114564/ce1c1fb4-cc71-4621-9c44-022c4a40fce0)
页面相关数据也未修改

**Comment by Nyakooo** [comment]
- 网络相应状态为只读，实际上是无法被修改的。插件只不过是在网络相应后到达视图层中间加了一层拦截。所以只看浏览者开发者工具中的响应是没有变化的。
- 可以通过命中数据验证是否有被拦截到。
  - 如果没有命中变化，排查一下匹配规则是否正确。
  - 排查一下是否同时启用同类的插件

**Comment by yangfeng20** [comment]
ok,明白了。是否能加一个命中拦截相关日志的功能。

**Comment by Nyakooo** [comment]
之前尝试过，但比较影响性能。所以就没有加

**Comment by yangfeng20** [comment]
感谢
