### ISSUE TITLE
插件

### ISSUE THREAD

**Issue by PPPPPPan** [g0ngjie/ajax-proxy#6]
![image](https://user-images.githubusercontent.com/87893615/181154840-6fb1cf74-2ae5-456f-8295-ad2a47e01d4d.png)

**Comment by PPPPPPan** [comment]
插件使用报错

**Comment by Nyakooo** [comment]
这段代码应该是创建新视图时所使用的，应该不会影响功能使用。
因为今年开始Chrome插件全部都改用V3版本 [Manifest V3](https://developer.chrome.com/blog/mv2-transition/)，所以此项目（V2版本）有些系统兼容的问题目前无法准确排查。
V2与V3版本部分Api差异较大。

V3版的插件正在开发当中。

**Comment by PPPPPPan** [comment]
似乎是一个BUG，导致的问题就是点击插件图标，窗口不弹出，解决方法是具体不详，我是让浏览器窗口全屏后，问题才解决

**Comment by Nyakooo** [comment]
![20220728-172648](https://user-images.githubusercontent.com/35398659/181471858-ce9f9c00-b98e-44ad-909f-61f445d7b242.gif)
这个问题确实无法复现，报的错误信息是提示V2版本将要废弃的警告。不知道会不会影响到测试。
如果有其他比较好的解决办法欢迎PR

Chrome 版本：103.0.5060.134（正式版本） （64 位）
Ajax Proxy版本：1.9.8

**Comment by Nyakooo** [comment]
全新版本插件已经上架 [Chrome 版本](https://chrome.google.com/webstore/detail/colibri-modify-ajax-respo/kalhaoeoppjgmbfdolmoeonfamnddkhc)、[Edge 版本](https://microsoftedge.microsoft.com/addons/detail/colibri-modify-ajax-resp/lfnnioheafobimpkhmdhgjodeobomcfl)
轻量级、支持协议拦截（GET、POST ...）、即时响应无需刷新
