### ISSUE TITLE
怎么设置状态码错误返回呢

### ISSUE THREAD

**Issue by biancangming** [g0ngjie/ajax-proxy#7]
在某些情况需要验证200、201、400、500的状态码

**Comment by Nyakooo** [comment]
目前暂不支持状态码的调整

**Comment by biancangming** [comment]
> 目前暂不支持状态码的调整

好的谢谢，但是感觉这个还是挺有用的，希望可以添加。有时候系统错误都是习惯写到500状态码里面，模拟出来，前端提示还是很棒的

**Comment by Nyakooo** [comment]
感谢支持，状态码这个需求后期会考虑加入进去。

**Comment by xiaoyi510** [comment]
快加入状态吗把 接口返回非200 只改数据不得劲

**Comment by Nyakooo** [comment]
版本2.0.1
